openapi: 3.0.3
info:
  title: Google Maps Scraper API
  version: 1.0.0
  description: API for managing job google maps scraping tasks

paths:
  /api/v1/jobs:
    post:
      summary: Create a new job scraping task
      x-code-samples:
        - lang: curl
          source: |
            curl -X POST "http://localhost:8080/api/v1/jobs" \
              -H "Content-Type: application/json" \
              -d '{
                "name": "Coffee shops Ilion",
                "keywords": ["coffee in ilion"],
                "lang": "el",
                "zoom": 15,
                "depth": 1,
                "max_time": 3600
              }'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiScrapeRequest'
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiScrapeResponse'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    get:
      summary: Get all jobs
      x-code-samples:
        - lang: curl
          source: |
            curl -X GET "http://localhost:8080/api/v1/jobs"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/jobs/{id}:
    get:
      summary: Get a specific job
      x-code-samples:
        - lang: curl
          source: |
            curl -X GET "http://localhost:8080/api/v1/jobs/6f0c1af8-3c4e-4742-84bb-590938ae8930"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '422':
          description: Invalid ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    delete:
      summary: Delete a specific job
      x-code-samples:
        - lang: curl
          source: |
            curl -X DELETE "http://localhost:8080/api/v1/jobs/455a6a00-cefb-4a9d-9e7d-791f01873700"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job deleted successfully
        '422':
          description: Invalid ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/jobs/{id}/download:
    get:
      summary: Download job results as CSV
      x-code-samples:
          source: |
            curl -X GET "http://localhost:8080/api/v1/jobs/18eafda3-53a9-4970-ac96-8f8dfc7011c3/download" --output results.csv
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '404':
          description: File not found
        '422':
          description: Invalid ID
        '500':
          description: Internal server error

components:
  schemas:
    ApiError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    ApiScrapeRequest:
      type: object
      properties:
        name:
          type: string
        keywords:
          type: array
          items:
            type: string
        lang:
          type: string
        zoom:
          type: integer
        lat:
          type: string
        lon:
          type: string
        fast_mode:
          type: boolean
        radius:
          type: integer
        depth:
          type: integer
        email:
          type: boolean
        max_time:
          type: integer
        proxies:
          type: array
          items:
            type: string
        use_croxy:
          type: boolean

    Entry:
      type: object
      properties:
        input_id:
          type: string
        link:
          type: string
        cid:
          type: string
        title:
          type: string
        categories:
          type: array
          items:
            type: string
        category:
          type: string
        address:
          type: string
        open_hours:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        popular_times:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: integer
        web_site:
          type: string
        phone:
          type: string
        plus_code:
          type: string
        review_count:
          type: integer
        review_rating:
          type: number
          format: float
        reviews_per_rating:
          type: object
          additionalProperties:
            type: integer
        latitude:
          type: number
          format: double
        longtitude:
          type: number
          format: double
        status:
          type: string
        description:
          type: string
        reviews_link:
          type: string
        thumbnail:
          type: string
        timezone:
          type: string
        price_range:
          type: string
        data_id:
          type: string
        images:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              image:
                type: string
        reservations:
          type: array
          items:
            type: object
            properties:
              link:
                type: string
              source:
                type: string
        order_online:
          type: array
          items:
            type: object
            properties:
              link:
                type: string
              source:
                type: string
        menu:
          type: object
          properties:
            link:
              type: string
            source:
              type: string
        owner:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            link:
              type: string
        complete_address:
          type: object
          properties:
            borough:
              type: string
            street:
              type: string
            city:
              type: string
            postal_code:
              type: string
            state:
              type: string
            country:
              type: string
        about:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              options:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    enabled:
                      type: boolean
        user_reviews:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              profile_picture:
                type: string
              rating:
                type: integer
              description:
                type: string
              images:
                type: array
                items:
                  type: string
              when:
                type: string
        user_reviews_extended:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              profile_picture:
                type: string
              rating:
                type: integer
              description:
                type: string
              images:
                type: array
                items:
                  type: string
              when:
                type: string
        emails:
          type: array
          items:
            type: string
        country_code:
          type: string
          description: "ISO country code (e.g., US, AU, ID)"
        opening_date:
          type: string
          description: "Business opening date"
        facebook:
          type: string
          description: "Facebook profile URL"
        instagram:
          type: string
          description: "Instagram profile URL"
        linkedin:
          type: string
          description: "LinkedIn profile URL"
        twitter:
          type: string
          description: "Twitter profile URL"
        opening_hours:
          type: string
          description: "Business opening hours"
        closing_hours:
          type: string
          description: "Business closing hours"
        is_open_24_hours:
          type: boolean
          description: "Whether the business is open 24 hours"
        is_closed:
          type: boolean
          description: "Whether the business is currently closed"
        use_croxy:
          type: boolean
        use_croxy:
          type: boolean

    ApiScrapeResponse:
      type: object
      properties:
        id:
          type: string

    Job:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        date:
          type: string
          format: date-time
        status:
          type: string
        data:
          $ref: '#/components/schemas/JobData'

    JobData:
      type: object
      properties:
        keywords:
          type: array
          items:
            type: string
        lang:
          type: string
        zoom:
          type: integer
        lat:
          type: string
        lon:
          type: string
        fast_mode:
          type: boolean
        radius:
          type: integer
        depth:
          type: integer
        email:
          type: boolean
        max_time:
          type: integer
        proxies:
          type: array
          items:
            type: string

